#!/usr/bin/env python
# -*- coding: utf-8 -*-

import wxversion
wxversion.select(wxversion.getInstalled()[0])
import wx
from PcWindow import PcWindow


class RiechOMat(wx.App):
    def OnInit(self):
        self.main = PcWindow(parent = None)
        self.main.Show()
        self.SetTopWindow(self.main)
        return True


def main():
    application = RiechOMat(0)
    application.MainLoop()


if __name__ == '__main__':
    main()
