#!/bin/bash

_temp="/tmp/answer.$$"
_temp2="/tmp/answer2.$$"
PN=`basename "$0"`
VER='0.4'
noisefile="/home/riech-o-mat/riech-o-mat/noise/white-noise-30min.ogg"
dialog 2>$_temp
DVER=`cat $_temp | head -1`

### Show Version 
version() {
    dialog --backtitle "Riech-O-Mat - an interactive smelling machine" \
           --msgbox "Version $VER \nStandalone minimal support version \n \nCoded, build and wired up in summer 2010 by J.U. Sommer" 9 52
}

### Show punchcard.txt
textbox() {
    filename="/home/riech-o-mat/riech-o-mat/punchcard.txt"
    if [ -e $filename ]; then
        dialog --backtitle "Riech-O-Mat - an interactive smelling machine"\
               --begin 3 5 --title " viewing punchcard.txt"\
               --textbox $filename 20 70
    else
        dialog --msgbox "*** ERROR ***\n punchcard.txt not found" 6 42
    fi
}

### Quit menu
quitmenu() {
        dialog --backtitle "Riech-O-Mat - an interactive smelling machine"\
               --title "Shutdown"\
               --yesno "Really shutdown Riech-O-Mat?" 6 20
case $? in
	#	0) rm $_temp; exit;;
		0) rm $_temp; /sbin/shutdown -h now;;
esac 
}

### Select Noise Menu
selnoise (){
	dialog --backtitle "Riech-O-Mat - an interactive smelling machine"\
               --title "Select noise"\
               --radiolist "Select kind of noise to use..." 11 35 9\
		01 "White noise" on\
		02 "Pink noise" off\
		03 "Brown noise" off\
		04 "Nature sounds" off 2> $_temp2
	noisefile=`cat $_temp2`

case $noisefile in
	01) noisefile="/home/riech-o-mat/riech-o-mat/noise/white-noise-30min.ogg";;
	02) noisefile="/home/riech-o-mat/riech-o-mat/noise/pink-noise-30min.ogg";;
	03) noisefile="/home/riech-o-mat/riech-o-mat/noise/brown-noise-30min.ogg";;
	04) noisefile="/home/riech-o-mat/riech-o-mat/noise/music.ogg";;
esac 
}



### create main menu using dialog
main_menu() {
    dialog --backtitle "Riech-O-Mat - an interactive smelling machine" --title "Riech-O-Mat Version $VER "\
        --cancel-label "Quit" \
        --menu "" 18 50 10\
        Start "Start Riech-O-Mat main program"\
        Edit "Edit punchcard file"\
        Show "Show punchcard file"\
        Info "Show Riech-O-Mat version info"\
 	Update "Update Riech-O-Mat Software"\
	Select-Noise "Select kind of noise"\
	Start-Noise "Start noise-playback"\
	Stop-Noise "Stop noise-playback"\
	Mixer "Open volume control"\
        Quit "Stop Riech-O-Mat" 2>$_temp\
        
    opt=${?}
    if [ $opt != 0 ]; then quitmenu; fi
    menuitem=`cat $_temp`
    echo "menu=$menuitem"
    case $menuitem in
        Start) /home/riech-o-mat/riech-o-mat/riech-o-mat;;
        Edit) mcedit /home/riech-o-mat/riech-o-mat/punchcard.txt;;
        Show) textbox;;
        Info) version;;
	Update) /home/riech-o-mat/riech-o-mat/update.sh;;
        Select-Noise) selnoise;;
        Mixer) /usr/bin/alsamixer;;
        Start-Noise) start-stop-daemon --background --start --name alsaplayer --startas /usr/bin/alsaplayer -- $noisefile -P --nosave;;
        Stop-Noise) start-stop-daemon --stop --name alsaplayer --startas /usr/bin/alsaplayer;;
        Quit) quitmenu;;
   esac
}

while true; do
  main_menu
done
